#[unstable]
#build-std = ['std', 'panic_abort']
[build]
target = "wasm32-wasi"
#target = "wasm32-unknown-unknown"

#[target.wasm32-wasi]
#rustflags = ["-C", "target-feature=+multivalue"]
#rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'
#[target.wasm32-unknown-unknown]
#rustflags = ["-C", "target-feature=+multivalue"]
#rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'
